Repository Team-Blitz-Steady/steady-client, pull requests merged in 2023-11, with the labels that each got.

#74 ✨ Feat(#73): 마이페이지 사이드바 레이아웃 (중간 머지)
  src/app/(user-menu)/mypage/layout.tsx
  src/app/(user-menu)/mypage/page.tsx
  src/app/layout.tsx
  src/components/_common/Icon/index.tsx
  src/components/_common/SideBar/index.tsx
Labels: 기능

#82 ✨ Feat(#75) 스테디 등록 페이지 구현
  src/app/(steady)/steady/create/page.tsx
  src/app/layout.tsx
  src/components/_common/Selector/Date/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/components/_common/Selector/Single/index.tsx
  src/components/ui/select.tsx
  src/constants/create-steady.ts
  tailwind.config.js
Labels: 기능

#87 ✨ Feat(#76): 스테디 수정 페이지 구현
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/Selector/Date/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/components/_common/Selector/Single/index.tsx
  src/constants/create-steady.ts
Labels: 기능

#72 ✨ Feat(#62): 신청서 수정 페이지 1차 구현
  src/app/(steady)/(application)/application/edit/[id]/page.tsx
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/components/application/Question.tsx
Labels: 기능

#80 ✨ Feat(#65): 신청서 양식 생성 페이지 1차 구현
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/page.tsx
Labels: 기능

#81 ✨ Feat(#66): 신청서 양식 수정 페이지 1차 구현
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
Labels: 기능

#85 💄 Style(#84): 공통 컴포넌트 StickyButton 배경 색 추가
  src/components/_common/StickyButton/index.tsx
Labels: 스타일

#86 🚨 Fix(#83): Main Page 오류 수정 및 재구현
  public/images/copyright.svg
  public/images/dolphin.png
  public/images/first.svg
  public/images/second.svg
  public/images/third.svg
  public/images/turtle.png
  public/images/walrus.png
  src/app/page.tsx
  src/components/Pagination/index.tsx
  tailwind.config.js
Labels: 에러

#92 ✨ Feat(#77): 마이 페이지(프로필 수정) 1차 구현
  public/images/kakaologo.png
  src/app/(user-menu)/mypage/page.tsx
  src/components/_common/Icon/index.tsx
Labels: 기능

#101 ✨ Feat(#98): 공통 컴포넌트 Input props 자동완성 기능 구현
  src/components/_common/Input/index.tsx
Labels: 기능

#99 ✨ Feat(#97): 공통 컴포넌트 Icon props 자동완성 기능 구현
  src/components/_common/Icon/index.tsx
Labels: 기능

#100 ✨ Feat(#88): HashTagInput 컴포넌트 추가
  src/components/_common/HashTagInput/index.tsx
  src/components/ui/toast.tsx
Labels: 기능

#91 ✨ Feat(#78): 내 스테디 목록 페이지 1차 구현
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/components/_common/Modal/AlertModal/index.tsx
  src/components/application/Title.tsx
Labels: 기능

#95 ✨ Feat(#93): 내가 받은 리뷰 페이지 1차 구현
  src/app/(user-menu)/mypage/page.tsx
  src/app/(user-menu)/mypage/reviews/page.tsx
Labels: 기능

#105 ✨ Feat(#104): AppBar 기능 추가
  package.json
  pnpm-lock.yaml
  src/components/_common/AppBar/index.tsx
  src/components/_common/Dropdown/index.tsx
  src/components/ui/scroll-area.tsx
Labels: 에러, 기능

#102 [Feat] - 신청자 목록 및 답변 열람 페이지 1차 구현
  src/app/(steady)/(application)/applicant/page.tsx
  src/app/(steady)/steady/applicant/[id]/page.tsx
  src/app/(steady)/steady/applicant/layout.tsx
  src/components/_common/SideBar/index.tsx
  src/components/application/Title.tsx
Labels: 기능

#109 🔨 Refactor(#94): Main Page 리팩터링
  public/images/logo.png
  public/images/steadyturtle.png
  public/images/stickybutton.svg
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/components/_common/StickyButton/index.tsx
  tailwind.config.js
Labels: 리팩터링

#112 ✨ Feat(#107): 스테디 질문 등록 페이지 구현
  src/app/(steady)/steady/create/questions/page.tsx
  src/app/layout.tsx
  src/components/ui/use-toast.ts
Labels: 기능

#114 Feat(#111): 404 페이지 구현
  public/images/notfound.png
  src/app/not-found.tsx
Labels: 기능

#118 ✨ Feat(#117): Query Client 생성 및 Provider 적용
  src/app/layout.tsx
  src/lib/react-query/QueryProvider.tsx
Labels: 기능

#119 ✨ Feat(#110): 피어 리뷰 페이지 1차 구현
  public/images/book.svg
  public/images/fire.svg
  public/images/heart.svg
  public/images/megafon.svg
  public/images/thumbs_up.svg
  src/app/(steady)/steady/review/[id]/page.tsx
Labels: 기능

#121 ✨ Feat(#113) oauth kakao 구현
  next.config.js
  src/app/layout.tsx
  src/app/logout/page.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SocialLoginStart.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/services/oauth/kakao/getKakaoLoginURL.ts
  src/services/oauth/kakao/getKakaoToken.ts
  src/stores/loginSteps.ts
  src/utils/cookies.ts
Labels: 기능

#131 ✨ Feat(#130): 타입 폴더 생성 및 카카오 토큰 타입 정의
  src/services/oauth/kakao/getKakaoToken.ts
  src/services/types/index.ts
Labels: 기능

#125 ✨ Feat(#122) Axios 인스턴스에 auth interceptor 적용
  src/services/index.ts
  src/services/oauth/kakao/getKakaoLoginURL.ts
  src/services/oauth/kakao/getKakaoToken.ts
  src/utils/cookies.ts
Labels: 기능

#132 ✨ Feat(#126): 스테디 상세 페이지 api 연동
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/components/Posts/index.tsx
  src/components/_common/Tag/index.tsx
  src/services/steady/getSteadyDetails.ts
  src/services/types/index.ts
Labels: 기능

#133 ✨ Feat(#127): 스테디 삭제 api 연동
  src/services/steady/deleteSteady.ts
Labels: 기능

#134 ✨ Feat(#128): 스테디 종료 api 연동
  src/services/steady/finishSteady.ts
Labels: 기능

#137 ✨ Feat(#129): 스테디 끌어올리기 api 연동
  src/services/steady/promoteSteady.ts
Labels: 기능

#139 ✨ Feat(#123): Private Route 설정
  src/middleware.ts
  src/utils/cookies.ts
Labels: 기능

#140 🚨 Fix(#136): 알림 Popover UI에 의한 에러 픽스
  src/components/_common/AppBar/index.tsx
Labels: 에러

#135 ✨ Feat(#108): 질문 수정 페이지 구현
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
Labels: 기능

#146 ✨Feat(#144): 신청서 상세 조회 api 연동
  src/app/(steady)/steady/applicant/[id]/page.tsx
  src/services/application/getApplicationDetails.ts
  src/services/types/index.ts
Labels: 기능

#143 ✨Feat(#138): 신청서 제출 api 연동
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/services/application/submitApplication.ts
Labels: 기능

#157 ✨ Feat(#141): 스테디 생성 API 연동 구현
  package.json
  pnpm-lock.yaml
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/create/questions/page.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/Selector/Date/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/components/_common/Selector/Single/index.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/constants/create-steady.ts
  src/constants/schemas/steadySchema.ts
  src/services/steady/createSteady.ts
  src/services/types/index.ts
  src/stores/createSteadyData.ts
  src/utils/extractValue.ts
  src/utils/formatDate.ts
Labels: 기능

#156 ✨ Feat(#151): 신청서 상태 변경 api 연결
  src/app/(steady)/steady/applicant/layout.tsx
  src/services/application/changeApplicationStatus.ts
  src/services/types/index.ts
  src/utils/extractValue.ts
Labels: 기능

#160 ✨ Feat(#155): 최초 로그인 시 유저 온보딩 구현
  src/components/_common/Icon/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContainer/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetInterestsAndStacks.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetNickname.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SocialLoginStart.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SteadyDescriptionEnd.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SteadyDescriptionStart.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/index.ts
  src/components/_common/Modal/LoginModal/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/schemas/setNickname.ts
  src/services/types/index.ts
  src/services/user/checkSameNickname.ts
  src/services/user/createUserProfile.ts
  src/stores/loginSteps.ts
  src/stores/newUserInfo.ts
  src/utils/extractValue.ts
Labels: 에러, 기능

#161 ✨ Feat(#120): Main Page API 연동
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/components/_common/Input/index.tsx
  src/services/steady/filterSteadies.ts
  src/services/steady/getSteadies.ts
  src/services/steady/searchSteadies.ts
  src/services/types/index.ts
Labels: 기능

#163 ✨Feat(#152): 내 템플릿 API 1차 연동
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/middleware.ts
  src/services/template/createTemplate.ts
  src/services/template/getTemplateDetail.ts
  src/services/template/getTemplates.ts
  src/services/types/index.ts
  src/utils/extractValue.ts
Labels: 기능

#168 ✨ Feat(#167): 스테디 생성 페이지에 기술 스택, 모집 분야 요청 API 적용
  src/app/(steady)/steady/create/loading.tsx
  src/app/(steady)/steady/create/page.tsx
  src/services/steady/getPositions.ts
  src/services/steady/getStacks.ts
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#169 ✨Feat(#162): 스테디 상세 페이지 구현
  package.json
  pnpm-lock.yaml
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/error.tsx
  src/app/loading.tsx
  src/app/logout/page.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/constants/create-steady.ts
  src/services/index.ts
  src/services/steady/getSteadyParticipants.ts
  src/services/types/index.ts
  src/utils/serverCookies.ts
Labels: 기능, 🔥 D-1

#166 ✨ Feat(#165): 템플릿 API 연동
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/components/_common/Modal/InputModal/index.tsx
  src/services/template/deleteTemplate.ts
  src/services/template/updateTemplate.ts
Labels: 기능

#173 ✨ Feat(#170): 내 신청서 관리 페이지 구현
  src/app/(user-menu)/mypage/application/page.tsx
  src/app/(user-menu)/mypage/layout.tsx
  src/components/_common/SideBar/index.tsx
Labels: 기능

#174 ✨ Feat(#142): 스테디 수정 페이지 폼 적용 및 API 연동
  src/app/(steady)/steady/edit/[id]/loading.tsx
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/Selector/Date/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/components/_common/Selector/Single/index.tsx
  src/constants/schemas/steadyEditSchema.ts
  src/services/steady/updateSteady.ts
Labels: 기능

#177 ✨ Feat(#176): 스테디 질문 수정 페이지 api 연동
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/loading.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
  src/services/steady/getSteadyQuestions.ts
  src/services/steady/updateSteady.ts
  src/services/steady/updateSteadyQuestions.ts
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#180 ✨ Feat(#164): Main Page API 2차 연동
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/components/_common/Icon/index.tsx
  src/components/_common/Input/index.tsx
  src/services/steady/filterSteadies.ts
  src/services/steady/getSteadies.ts
  src/services/steady/searchSteadies.ts
Labels: 기능, 🚨 D-0

#184 ✨ Feat(#183): 쿠키 관리 로직 수정
  src/app/(auth)/clear/page.tsx
  src/app/(auth)/login/route.ts
  src/app/(auth)/logout/route.ts
  src/app/(user-menu)/mysteady/page.tsx
  src/app/layout.tsx
  src/app/logout/page.tsx
  src/components/_common/AppBar/index.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/stores/createSteadyData.ts
  src/stores/isAuth.ts
Labels: 에러, 🚨 D-0

#179 ✨Feat(#172): 내 스테디 목록 페이지 구현
  package.json
  pnpm-lock.yaml
  src/app/(user-menu)/mysteady/page.tsx
  src/hooks/useMySteadiesQuery.ts
  src/hooks/useScrollTo.ts
  src/services/steady/getMySteadies.ts
  src/services/types/index.ts
Labels: 기능, 🔥 D-1

#185 ✨Feat(#171): 신청서 제출 페이지 구현
  src/app/(steady)/(application)/application/layout.tsx
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/components/application/Title.tsx
  src/schemas/setNickname.ts
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#193 🔥🚨 Fix(#190): 쿠키 에러 1차 핫픽스
  src/app/(auth)/login/route.ts
  src/app/(auth)/logout/route.ts
  src/components/_common/Modal/LoginModal/index.tsx
Labels: 에러, 🚨 D-0

#194 ✨Feat(#192): 유저 관련 api
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/services/steady/getPositions.ts
  src/services/steady/getStacks.ts
  src/services/types/index.ts
  src/services/user/createUserProfile.ts
  src/services/user/getMyProfile.ts
  src/services/user/getUserProfile.ts
  src/services/user/updateMyProfile.ts
  src/stores/newUserInfo.ts
Labels: 에러, 기능, 🔥 D-1

#196 ✨ Feat(#195): 알림 관련 api
  src/services/notification/deleteAllNotifications.ts
  src/services/notification/deleteNotification.ts
  src/services/notification/getAllNotifications.ts
  src/services/notification/readAllNotifications.ts
  src/services/notification/readNotification.ts
  src/services/types/index.ts
Labels: 기능, 🔥 D-1

#198 🔥🚨 Fix(#197): 쿠키 에러 2차 핫픽스
  src/app/(auth)/api/login/route.ts
  src/app/(auth)/api/logout/route.ts
  src/app/(auth)/clear/page.tsx
  src/app/(auth)/logout/page.tsx
  src/components/_common/Modal/LoginModal/index.tsx
Labels: 기능, 🚨 D-0

#204 🚨 Fix(#182): 스테디 등록 페이지 1차 QA 반영
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/create/questions/page.tsx
  src/components/_common/Selector/Date/index.tsx
  src/stores/createSteadyData.ts
  src/utils/isPastDate.ts
Labels: 에러, 🚨 D-0

#205 💄 Style(#199): 스테디 등록 페이지 디자인 변경
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/create/questions/page.tsx
  src/components/_common/Input/index.tsx
  src/constants/create-steady.ts
Labels: 스타일, 🚨 D-0

#209 🚨 Fix(#207): 로그아웃 실패 시 직접 쿠키 만료 헤더 응답 전송
  src/app/(auth)/api/logout/route.ts
Labels: 에러, 🚨 D-0

#203 ✨ Feat(#201): 템플릿 삭제 버튼 생성 및 삭제 이슈 해결
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
Labels: 기능, 🔥 D-1

#208 ✨ Feat(#202): 리뷰 페이지 스테디 정보 추가
  src/app/(steady)/steady/review/[id]/page.tsx
  tailwind.config.js
Labels: 기능

#210 💄 Style(#206): 스테디 수정 페이지 외형 변경
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/constants/create-steady.ts
Labels: 스타일, 🚨 D-0

#200 ✨Feat(#189) Main Page API 3차 연동
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/services/steady/filterSteadies.ts
  src/services/steady/getSteadies.ts
  src/services/steady/searchSteadies.ts
Labels: 기능, 🔥 D-1

#191 ✨Feat(#187): 신청자 목록 및 답변 열람 페이지 구현
  src/app/(steady)/steady/applicant/[id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/loading.tsx
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/layout.tsx
  src/app/(steady)/steady/applicant/[steady_id]/page.tsx
  src/app/(steady)/steady/applicant/layout.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/components/_common/Modal/UserModal/UserItems.tsx
  src/components/_common/Modal/UserModal/index.tsx
  src/constants/userCards.ts
  src/hooks/query/useMySteadiesQuery.ts
  src/services/application/changeApplicationStatus.ts
  src/services/types/index.ts
Labels: 기능, 🔥 D-1

#216 ✨ Feat(#213): 신청자 목록 및 답변 열람 페이지 스타일 및 추가 구현
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/loading.tsx
  src/app/(steady)/steady/applicant/[steady_id]/layout.tsx
  src/app/(user-menu)/chat/[user_id]/page.tsx
  src/app/global.css
  src/components/_common/Icon/index.tsx
  src/components/_common/Modal/UserModal/UserCards.tsx
  src/components/_common/Modal/UserModal/UserItems.tsx
  src/components/_common/Modal/UserModal/index.tsx
  src/constants/userCards.ts
  src/hooks/query/useApplicantListQuery.ts
  src/services/application/getApplicationsList.ts
Labels: 기능, 스타일, 🔥 D-1

#220 🚨 Fix(#218): 템플릿 생성 이슈
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
Labels: 에러

#217 ✨ Feat(#214): 알림 기능 구현
  src/components/_common/AppBar/index.tsx
  src/components/ui/scroll-area.tsx
Labels: 기능, 🚨 D-0

#222 ✨Feat(#211): 스테디 상세페이지 재 디자인
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/components/_common/Icon/index.tsx
  src/components/_common/Modal/InfoModal/index.tsx
  src/components/_common/Modal/UserModal/UserItems.tsx
  src/services/steady/likeSteady.ts
  src/services/types/index.ts
  tailwind.config.js
Labels: 스타일

#223 ✨Feat(#188): 내 리뷰 페이지 구현
  src/app/(auth)/logout/page.tsx
  src/app/(user-menu)/mypage/reviews/page.tsx
  src/components/_common/Icon/index.tsx
  src/middleware.ts
  src/services/index.ts
  src/services/review/changeReviewStatus.ts
  src/services/review/createReview.ts
  src/services/review/getMyReviews.ts
  src/services/types/index.ts
  src/utils/cookieService.ts
Labels: 기능, 🔥 D-1

#226 🚨Hotfix(#225): 신청자 목록 및 답변 열람 페이지 버그 수정
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/layout.tsx
  src/app/(steady)/steady/applicant/[steady_id]/page.tsx
  src/hooks/query/useApplicantListQuery.ts
  src/services/application/getApplicantList.ts
  src/services/types/index.ts
Labels: 에러, 🚨 D-0

#230 💄 Style(#227): 백엔드 수정 사항 반영
  src/app/(user-menu)/mypage/reviews/page.tsx
Labels: 에러, 스타일

#232 🚨 Fix(#229): 스테디 수정 페이지 핫픽스
  src/app/(steady)/steady/edit/[id]/page.tsx
Labels: 에러, 🚨 D-0

#234 ✨ Feat(#212): Main Page 4차 API 연동
  public/images/no_result.png
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/constants/create-steady.ts
  src/services/steady/filterSteadies.ts
  src/services/steady/getSteadies.ts
  src/services/types/index.ts
Labels: 기능, 🔥 D-1

#233 ✨Feat(#186): 참여 신청서 수정 페이지 구현
  src/app/(steady)/(application)/application/edit/[id]/page.tsx
  src/app/(steady)/(application)/application/edit/[steady_id]/[application_id]/page.tsx
  src/services/application/editApplication.ts
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#240 ✨ Feat(#219): 질문 등록 / 수정 페이지 질문 추가 기능 개선
  src/app/(steady)/steady/create/questions/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
Labels: 기능, 🚨 D-0

#241 ✨ Feat(#238): 회원용 기능 진입점에 로그인 의사 확인 모달 적용
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/page.tsx
Labels: 기능, 🚨 D-0

#242 ✨ Feat(#231) 내 신청서 목록 API 연동
  src/app/(user-menu)/mypage/application/page.tsx
  src/hooks/query/useApplicationListQuery.ts
  src/services/application/deleteApplication.ts
  src/services/application/getApplicationList.ts
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#245 🚨Fix(#244): 여러 수정 사항들 반영 완료
  public/images/DeleteUser.svg
  src/app/(steady)/(application)/application/edit/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
  src/app/(user-menu)/mypage/reviews/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/app/page.tsx
  src/components/_common/Modal/UserModal/UserItems.tsx
  src/constants/queryKeys.ts
  src/hooks/query/useApplicantListQuery.ts
  src/hooks/query/useApplicationListQuery.ts
  src/hooks/query/useMySteadiesQuery.ts
  src/services/types/index.ts
Labels: 에러

#248 ✨Feat(#224): 스테디 상세 페이지 디자인 변경 및 api 연결
  next.config.js
  src/app/(steady)/(application)/application/edit/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
Labels: 기능, 스타일, 🔥 D-1

#249 ✨ Feat(#239): 내 프로필 페이지 API 연동
  src/app/(auth)/api/login/route.ts
  src/app/(user-menu)/mypage/page.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetPositionAndStacks.tsx
  src/schemas/setNickname.ts
  src/schemas/userBioSchema.ts
  src/services/user/deleteMyProfile.ts
  src/services/user/updateMyProfile.ts
Labels: 기능, 🚨 D-0

#251 ✨ Feat(#243): 내 좋아요 및 인기 스테디 API 연동
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/components/_common/AppBar/index.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/NavigationBar/index.tsx
  src/components/_common/StickyButton/index.tsx
  src/components/_common/Tag/index.tsx
  src/services/steady/filterSteadies.ts
  src/services/steady/getPopularSteadies.ts
  src/services/steady/getSteadies.ts
Labels: 기능, 🚨 D-0

#259 ✨ Feat(#256): 질문 등록 / 수정 페이지 템플릿 정보 불러오기 / 질문 템플릿으로 저장하기 기능 추가
  src/app/(steady)/steady/create/questions/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
  src/constants/selectorItems.ts
Labels: 기능, 🚨 D-0

#258 ✨ Feat(#257): 템플릿 페이지 취소하기 버튼 추가
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
Labels: 기능, 🚨 D-0

#263 🔨 Refactor(#262): 내 신청서 페이지 리팩터링
  src/app/(user-menu)/mypage/application/page.tsx
  src/services/types/index.ts
Labels: 리팩터링, 🚨 D-0

#253 ✨Feat(#252): 추가 구현 완
  src/app/(steady)/(application)/application/loading.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(steady)/steady/loading.tsx
  src/app/(user-menu)/mypage/loading.tsx
  src/app/(user-menu)/mysteady/loading.tsx
  src/app/client/page.tsx
  src/app/error.tsx
  src/app/loading.tsx
  src/app/page.tsx
  src/components/_common/Button/index.tsx
  src/components/_common/Modal/InfoModal/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContainer/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SelectedSteadyAction.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/index.ts
  src/components/_common/Modal/LoginModal/index.tsx
  src/constants/queryKeys.ts
  src/hooks/mutation/useLikeSteadyMutation.ts
  src/lib/react-query/QueryProvider.tsx
  src/services/index.ts
  src/stores/isSearchBarFocus.ts
  src/stores/loginModalOpen.ts
Labels: 에러, 기능, 🚨 D-0

#264 ✨ Feat(#221): 리뷰 페이지 API 구현
  src/app/(steady)/steady/review/[id]/page.tsx
  src/constants/queryKeys.ts
  src/services/review/getReviewCards.ts
  src/services/review/getReviewSteadyInfo.ts
  src/services/types/index.ts
Labels: 기능

#266 ✨ Feat(#260): 프로필 이미지 수정 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(steady)/steady/create/questions/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
  src/app/(steady)/steady/manage/[id]/page.tsx
  src/app/(user-menu)/mypage/page.tsx
  src/components/_common/ProfileImageUpload/index.tsx
  src/components/ui/accordion.tsx
  src/services/types/index.ts
  src/services/user/getProfileImageLink.ts
Labels: 기능

#265 🔨 Refactor(#254): 메인페이지 리팩터링
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
  src/components/_common/AppBar/index.tsx
  src/components/_common/Footer/index.tsx
  src/components/_common/Tag/index.tsx
  src/stores/page.ts
Labels: 리팩터링, 🔥 D-1

#274 💄Style(#268): 내 스테디 페이지 반응형 구현
  src/app/(user-menu)/mysteady/page.tsx
  src/app/page.tsx
  src/components/_common/NavigationBar/index.tsx
Labels: 스타일, 🚨 D-0

#277 💄 Style(#267): 상세 페이지 반응형 구현
  src/app/(steady)/steady/detail/[id]/page.tsx
Labels: 스타일, 🚨 D-0

#278 🚨 Fix(#270): 2nd QA 사항 반영
  src/app/(user-menu)/mypage/page.tsx
  src/app/error.tsx
  src/components/_common/Input/index.tsx
  src/react-query.d.ts
  src/services/types/index.ts
Labels: 에러, 🚨 D-0

#276 🔨 Refactor(#273): 생성일 코드 수정
  src/app/(user-menu)/mypage/template/page.tsx
  src/components/_common/Footer/index.tsx
Labels: 리팩터링

#281 💄 Style(#280): 마이 페이지 반응형 구현
  src/app/(user-menu)/mypage/application/page.tsx
  src/app/(user-menu)/mypage/layout.tsx
  src/app/(user-menu)/mypage/page.tsx
  src/app/(user-menu)/mypage/reviews/page.tsx
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/components/_common/SideBar/index.tsx
  src/constants/commonStyle.ts
Labels: 스타일, 🚨 D-0

#283 💄 Style(#282): 신청자 목록 및 답변 열람 페이지 반응형 구현
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/layout.tsx
  src/app/(steady)/steady/applicant/[steady_id]/page.tsx
  src/app/(steady)/steady/applicant/layout.tsx
Labels: 스타일, 🚨 D-0

#285 💄 Style(#284): 신청서 생성 및 수정 페이지 반응형 구현
  src/app/(steady)/(application)/application/layout.tsx
  src/components/application/Title.tsx
Labels: 스타일, 🚨 D-0

#279 ✨ Feat(#271): 스테디 멤버 추방 api 연동
  src/app/(steady)/steady/manage/[id]/page.tsx
  src/services/steady/deleteSteadyMember.ts
Labels: 기능, 🚨 D-0

#275 ✨ Feat(#269): 내 신청서 및 템플릿 삭제 확인 모달 추가
  src/app/(user-menu)/mypage/application/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/components/_common/Modal/DeleteModal/index.tsx
Labels: 기능

#295 ✨ Feat(#261): 마크다운 에디터 적용 (등록, 상세보기, 수정 페이지)
  package.json
  pnpm-lock.yaml
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/app/client/page.tsx
  src/app/layout.tsx
  src/components/_common/Editor/ForwardedRefEditor.tsx
  src/components/_common/Editor/InitializedMDXEditor.tsx
  tailwind.config.js
Labels: 기능, 🚨 D-0

#290 ✨ Feat(#272): 메인페이지 반응형 작업
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/components/Posts/index.tsx
  src/components/_common/AppBar/index.tsx
  src/components/_common/NotificationPopup/index.tsx
Labels: 기능, 🚨 D-0

#296 💄Style(#293): 모달 반응형 구현 및 스타일링 통일
  src/app/(steady)/steady/manage/[id]/page.tsx
  src/app/(user-menu)/mypage/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/components/_common/Modal/UserModal/UserItems.tsx
  src/components/_common/Modal/UserModal/index.tsx
Labels: 스타일, 🚨 D-0

#292 ✨Feat(#287): 내 스테디 연락수단 클립 보드 구현
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/services/types/index.ts
Labels: 기능, 🚨 D-0

#301 💄 Style(#291): 템플릿 페이지 반응형 작업
  src/app/(user-menu)/mypage/template/create/page.tsx
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
  src/app/(user-menu)/mypage/template/page.tsx
  src/components/TabBar/index.tsx
Labels: 스타일, 🚨 D-0

#304 🚨 Fix(#303): 메인페이지 코드 수정
  src/app/page.tsx
Labels: 에러, 🚨 D-0

#299 💄Style(#286): 스테디 관련 페이지 반응형 완료
  src/app/(steady)/steady/create/page.tsx
  src/app/(steady)/steady/create/questions/page.tsx
  src/app/(steady)/steady/edit/[id]/page.tsx
  src/app/(steady)/steady/edit/questions/[id]/page.tsx
  src/app/(steady)/steady/manage/[id]/page.tsx
  src/components/_common/Input/index.tsx
Labels: 스타일, 🚨 D-0

#305 🚨 Fix(#298): 상세 페이지 좋아요 api 수정 및 에러 페이지 새로고침 버튼 추가
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/error.tsx
Labels: 에러, 기능, 🚨 D-0
