Repository Team-Blitz-Steady/steady-client, pull requests merged in 2023-10, with the labels that each got.

#29 ✨ Feat: #13 Avatar 공통 컴포넌트 추가
  src/app/page.tsx
  src/components/_common/Avatar/index.tsx
Labels: 기능

#30 ✨ Feat: #13 Spinner 공통 컴포넌트 추가
  src/components/_common/Spinner/index.tsx
Labels: 기능

#24 ✨ Feat: #6 - 공통 컴포넌트 Button 추가
  src/components/_common/Button/index.tsx
Labels: 기능

#22 ✨ Feat: #2 - 공통 컴포넌트 SideBar 추가
  src/components/_common/SideBar/index.tsx
  tailwind.config.js
Labels: 기능

#36 ✨ Feat: #9 - 공통 컴포넌트 Logo 추가
  public/images/logo.png
  src/components/_common/Logo/index.tsx
Labels: 기능

#37 ✨ Feat: #5 - 공통 컴포넌트 Input 추가
  src/components/_common/Input/index.tsx
  tailwind.config.js
Labels: 기능

#28 ✨ Feat: #3 - 공통 컴포넌트 ListItem 추가
  src/components/_common/ListItem/index.tsx
Labels: 기능

#34 ✨ Feat: #11 - 공통 컴포넌트 Icon 추가
  src/components/_common/Icon/index.tsx
Labels: 기능

#39 ✨ Feat: #38 - 공통 컴포넌트 Button props 추가
  src/components/_common/Button/index.tsx
Labels: 기능

#33 ✨ Feat: #15 - 공통 컴포넌트 StickyButton 추가
  public/images/stickybutton.svg
  src/components/_common/StickyButton/index.tsx
Labels: 기능

#32 ✨ Feat: #18 - 공통 컴포넌트 Line 추가
  src/components/_common/Line/Index.tsx
  src/components/_common/Line/index.tsx
Labels: 기능

#45 ✨ Feat: #42 - 공통 컴포넌트 Icon 재구현
  src/components/_common/Icon/index.tsx
  tsconfig.json
Labels: 기능

#44 🚨 Fix(#41): commitlint 이슈 해결
  .husky/commit-msg
  commitlint.config.js
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
Labels: 에러

#49 🔨 Refactor(#40): Icon 컴포넌트 적용, width도 조건부 적용
  src/components/_common/ListItem/index.tsx
Labels: 리팩터링

#50 🚨 Style(#48) Root Layout 공통 스타일 및 헤더 적용
  src/app/layout.tsx
  tailwind.config.js
Labels: 스타일

#46 ✨ Feat: #4 - 공통 컴포넌트 Modal 구현
  src/components/_common/Button/index.tsx
  src/components/_common/Modal/AlertModal/index.tsx
  src/components/_common/Modal/InfoModal/index.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/components/_common/Modal/UserModal/index.tsx
  src/components/_common/Modal/index.ts
Labels: 기능

#56 🚨 Fix(#55): Avatar 컴포넌트 에러 수정 외 1건
  package.json
  pnpm-lock.yaml
  src/components/_common/Avatar/index.tsx
Labels: 에러

#54 💄 Style(#53): 공통 컴포넌트 StickyButton position 조정
  src/components/_common/StickyButton/index.tsx
Labels: 스타일

#58 🚨 Fix(#57): Icon 컴포넌트 오류 해결
  src/components/_common/Icon/index.tsx
Labels: 에러

#71 ✨ Feat(#61): 신청서 작성 페이지 1차 구현
  src/app/(steady)/(application)/application/layout.tsx
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/components/application/Question.tsx
  src/components/application/Title.tsx
  src/components/application/index.ts
Labels: 기능

#59 ✨ Feat(#52): 로그인 절차 모달 구현
  public/images/kakaobutton.png
  public/images/steadytext.png
  public/images/steadyturtle.png
  src/components/_common/AppBar/index.tsx
  src/components/_common/Button/index.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContainer/index.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetInterestsAndStacks.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SetNickname.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SocialLoginEnd.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SocialLoginStart.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SteadyDescriptionEnd.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/SteadyDescriptionStart.tsx
  src/components/_common/Modal/LoginModal/LoginStepsContents/index.ts
  src/components/_common/Modal/LoginModal/index.tsx
  src/components/_common/Modal/index.ts
  src/stores/loginSteps.ts
Labels: 기능

#60 ✨ Feat(#51): 1차 스테디 상세 페이지 구현
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/components/_common/Tag/index.tsx
Labels: 기능

#68 ✨ Feat(#20) Selector 공통 컴포넌트 부분 구현
  package.json
  pnpm-lock.yaml
  src/components/_common/Selector/Date/index.tsx
  src/components/_common/Selector/Multi/index.tsx
  src/components/_common/Selector/Single/index.tsx
  src/components/_common/Selector/core/button.tsx
  src/components/_common/Selector/core/calendar.tsx
  src/components/_common/Selector/core/command.tsx
  src/components/_common/Selector/core/popover.tsx
  src/components/_common/Selector/core/select.tsx
  src/components/_common/Selector/index.ts
  src/components/_common/Selector/types/selectItem.ts
  tailwind.config.js
Labels: 기능

#70 💄 Style(#69): 공통 컴포넌트 Stickybutton position 코드 제거
  src/components/_common/StickyButton/index.tsx
Labels: 스타일
