Repository Team-Blitz-Steady/steady-client, pull requests merged in 2023-12, with the labels that each got.

#307 🚨 Fix(#300): 3차 QA 부분 수정
  src/components/_common/AppBar/index.tsx
  src/components/_common/Dropdown/index.tsx
  src/components/_common/Editor/InitializedMDXEditor.tsx
  src/components/_common/NotificationPopup/index.tsx
  src/components/_common/Selector/Multi/index.tsx
Labels: 에러, 🚨 D-0

#308 💄 Style(#302): 리뷰 페이지 반응형 작업
  src/app/(steady)/steady/review/[id]/page.tsx
Labels: 스타일, 🔥 D-1

#311 ✨ Feat(#306): open graph 적용
  src/app/layout.tsx
  src/app/shared-metadata.ts
Labels: 기능

#314 ✨Feat(#313): 스테디 상세 페이지에 연락수단 클립보드 기능 추가
  src/app/(steady)/steady/detail/[id]/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/components/_common/ContactTag/index.tsx
  src/hooks/useCopySteadyContact.ts
Labels: 기능, 🚨 D-0

#316 🚨Fix(#315) - QA 내용 반영
  public/font/Pretendard-Black.woff
  public/font/Pretendard-ExtraBold.woff
  public/font/Pretendard-ExtraLight.woff
  public/font/Pretendard-Light.woff
  public/font/Pretendard-Thin.woff
  src/app/(steady)/(application)/application/[steady_id]/[application_id]/page.tsx
  src/app/(user-menu)/mypage/application/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/app/global.css
  src/components/TabBar/index.tsx
  src/components/_common/AppBar/AuthAppBar.tsx
  src/components/_common/AppBar/index.tsx
  src/components/_common/Dropdown/index.tsx
  src/components/application/Title.tsx
Labels: 🚨 D-0

#320 🚨 Fix(#319): 4차 QA 사항 반영
  src/app/(user-menu)/mypage/page.tsx
  src/app/error.tsx
  src/components/_common/Dropdown/index.tsx
  src/components/_common/Input/index.tsx
  src/components/_common/NotificationPopup/index.tsx
  src/components/_common/ProfileImageUpload/index.tsx
Labels: 에러, 🚨 D-0

#325 ✨ Feat(#324): 로그인 온보딩 웰컴 모달 구현
  src/app/page.tsx
  src/components/_common/Modal/LoginModal/index.tsx
  src/components/_common/Modal/WelcomeModal/WelcomeModalContainer.tsx
  src/components/_common/Modal/WelcomeModal/index.tsx
  src/stores/welcomeModalOpen.ts
Labels: 기능

#334 🚨 Fix(#333): 스테디 수정 시 포지션과 스택을 선택하지 않은 채로 수정이 되는 현상 수정
  src/schemas/steadySchema.ts
Labels: 에러, 🚨 D-0

#335 🚨 Fix(#326): 템플릿 오류 수정
  src/app/(user-menu)/mypage/template/edit/[id]/page.tsx
Labels: 에러

#336 Refactor/#332/mysteady
  src/app/(auth)/logout/page.tsx
  src/app/(steady)/(application)/application/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/(application)/application/edit/[steady_id]/[application_id]/page.tsx
  src/app/(steady)/(application)/application/submit/[id]/page.tsx
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/app/(user-menu)/mysteady/page.tsx
  src/app/error.tsx
  src/components/_common/Title/index.tsx
  src/components/containers/application/Question.tsx
  src/components/containers/application/Title.tsx
  src/components/containers/application/index.ts
  src/components/containers/mysteady/EmptySteady.tsx
  src/components/containers/mysteady/Steadies.tsx
  src/components/containers/mysteady/SteadyFilter.tsx
  src/components/containers/mysteady/constants/index.ts
  src/components/containers/mysteady/utils/emptySteadiesMessage.ts
Labels: 스타일, 리팩터링

#340 Refactor/#337/applicant
  src/app/(steady)/steady/applicant/[steady_id]/[application_id]/page.tsx
  src/components/containers/applicant/ApplicantButtons.tsx
  src/components/containers/applicant/hooks/useManageApplicant.ts
Labels: 리팩터링

#341 Refactor/#338/myreview
  src/app/(user-menu)/mypage/reviews/page.tsx
  src/components/containers/myReviews/MyCardReview.tsx
  src/components/containers/myReviews/MyCommentReview.tsx
Labels: 리팩터링

#344 🔨 Refactor(#331): 메인페이지 리팩터링
  src/app/page.tsx
  src/components/Pagination/index.tsx
  src/components/Posts/index.tsx
Labels: 리팩터링, 🚨 D-0
